up

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -15,6 +15,13 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
+      - name: Stop if not confirmed
+        run: |
+          if [ "${{ github.event.inputs.confirm }}" != "DESTROY" ]; then
+            echo "Confirmation failed. Type DESTROY to proceed."
+            exit 1
+          fi
+          
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -27,6 +34,7 @@ jobs:
         with:
           terraform_version: 1.5.0
 
+
       - name: Terraform Init
         run: terraform init
 
@@ -34,6 +42,7 @@ jobs:
         env:
           TF_VAR_region: ${{ secrets.AWS_REGION }}                      
           TF_VAR_ecr_repo_url: ${{ secrets.ECR_REPO_URL }} 
+          TF_VAR_image_tag: "latest"
           TF_VAR_db_name: ${{ secrets.DB_NAME }}
           TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
           TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
